### ISSUE TITLE
419 PAGE EXPIRED

### ISSUE THREAD

**Issue by gfsoluzioni** [open-admin-org/open-admin#131] opened 2024-01-05 12:17 UTC
Hi I just installed open-admin on my laravel version 10, but I encountered a problem during the authentication process.
When I enter my username and password I am redirected to a page with the following content:

The information you are about to send is not protected
Your information will be visible to other users because the form will be submitted over an insecure connection.

When I click on "Send anyway" I get the following error: 419 PAGE EXPIRED.

How can I solve this problem?? My domain supports an SSL certificate and I have automatic redirection to https enabled by default.

I await your replies.
Thank you

**Comment by RCyrix** [comment] 2024-01-06 16:04
Hi there

Check under config/admin.php 

Theres a flag for HTTPS 

By default i think its set to false, 

Checkout that flag, when putting an application into production I had the same thing and it was just the https flag 

Content was being requested on incorrect schema 

![image](https://github.com/open-admin-org/open-admin/assets/124294361/7728daec-0a1a-4057-8cd2-1cf6f1ca93a8)

**Comment by AliHassan002** [comment] 2024-01-10 07:24
hello @RCyrix , i just want to ask , this is what showing for me. Should i just change it to **true** . is there any other change or requirement need to run the application on production.. Kindly let me know.

'https' => env('ADMIN_HTTPS', false),

**Comment by RCyrix** [comment] 2024-01-10 08:07
if you are experiencing the same issue try it ? It wont break anything if you change a flag and refresh..

**Comment by AliHassan002** [comment] 2024-01-10 08:36
@RCyrix , in my local development it's not creating an issue . but on the production i'm getting the error. 
Also, kindly can you explain what is flag and what do you mean by it. i'm not be able to get it.

**Comment by RCyrix** [comment] 2024-01-10 13:53
flag means value can be true or false or whatever representation of true or false like 0 or 1, 

The only time i have seen this error is due to https config in config/admin.php

**Comment by AliHassan002** [comment] 2024-01-10 14:04
@RCyrix thanks alot man for taking your time to answer.

**Comment by RCyrix** [comment] 2024-01-13 03:36
Hi guys, if the issue is sorted may I ask that you close it? 

It does not give me the option

**Closed as completed** 2024-01-18 14:03 UTC
